default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: classified_db
  username: fredbanda
  password: fred80
  host: localhost
  port: 5432

test:
  <<: *default
  database: eunny_classified_web_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

